version: 0.2
env:
  runtime-versions:
    nodejs: 22
phases:
  install:
    commands:
      - echo "Installing Node.js 22 manually..."
      - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
      - export PATH=/usr/bin:$PATH
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v

      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://my-vue-app-bucket-shelves --delete
artifacts:
  files:
    - '**/*'