version: 0.2
env:
  runtime-versions:
    nodejs: 22
phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
        - apt-get install -y nodejs
        - export PATH=/usr/bin:$PATH
        - node -v
        - npm -v
        - echo "INSTALL complete"
  build:
    commands:
        - echo "Current directory: $(pwd)"
        - ls -la
        - echo "Trying to cd into frontend/app..."
        - cd frontend/app || (echo "Directory not found — dumping tree:" && find . -type d && exit 1)
        - npm install
        - npm run build
        - echo "Build complete — dumping dist:"
        - ls -la dist

  post_build:
    commands:
       - aws s3 sync frontend/app/dist/ s3://my-vue-app-bucket-shelves --delete
artifacts:
  files:
    - '**/*'