version: 0.2
env:
  runtime-versions:
    nodejs: 22
phases:
  install:
    commands:
      - echo "Installing Node.js 22 manually..."
      - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
      - export PATH=/usr/bin:$PATH
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v

      - cd frontend/app/
      - npm install
  build:
    commands:
      - cd frontend/app
        - echo "Running build from $(pwd)"
        - npm run build
        - echo "Build complete — dumping contents:"
        - ls -la
  post_build:
    commands:
      - echo "Checking dist folder before sync..."
      - ls -la frontend/app/dist || echo "dist folder not found"
      - aws s3 sync frontend/app/dist/ s3://my-vue-app-bucket-shelves --delete
artifacts:
  files:
    - '**/*'