version: 0.2
env:
  runtime-versions:
    nodejs: 22
phases:
  install:
    commands:
      - cd frontend/app
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync frontend/app/dist/ s3://your-s3-bucket-name --delete
artifacts:
  files:
    - '**/*'