version: 0.2
env:
  runtime-versions:
    nodejs: 22
phases:
  install:
    commands:
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v
      - echo "Available Node versions:"
      - ls /opt/nodejs
      - echo "System PATH:"
      - echo $PATH
      - cd frontend/app
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://my-vue-app-bucket-shelves --delete
artifacts:
  files:
    - '**/*'